- name: Copy of file to all hosts
  hosts: webservers
  become: true
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /home/ec2-user/testfile1
        dest: /home/ec2-user/testfile1
        when: ansible_facts['os_family'] == "Debian"
    
- name: Coppy the files
  hosts: ubuntuservers
  become: true
  tasks:
    - name: Copy files with owner and permissions
      ansible.builtin.copy:
        src: /home/ec2-user/testfile1
        dest: /home/ubuntu/testfile1
        
        