- name: Copy of file to all hosts
  hosts: webservers
  become: true
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /home/ec2-user/testfile1
        dest: /home/ec2-user/testfile1
        when: ansible_facts['os_family'] == "Debian"
        mode: u+rw,g-wx,o-rwx

- name: Coppy the files
  hosts: ubuntuservers
  become: true
  tasks:
    - name: Copy files with owner and permissions
      ansible.builtin.copy:
        src: /home/ec2-user/testfile1
        dest: /home/ubuntu/testfile1
        mode: u+rw,g-wx,o-rwx

- name: Copy for node1
  hosts: node1
  tasks:
    - name: Another symbolic mode example, adding some permissions and removing others
      ansible.builtin.copy:
        content: 'This is content of file2'
        dest: /home/ec2-user/testfile2

    - name: Create a new text file
      ansible.builtin.shell: "echo Hello World > /home/ec2-user/testfile3"